# This file provides instructions for packaging.

`Module-Install-Copyright`
	perl_version_from m`Module::Install::Copyright`;
	version_from      m`Module::Install::Copyright`;
	readme_from       m`Module::Install::Copyright`;
	test_requires     p`Test::More 0.61` ;
	.

